// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 6/19/2024, 4:09:49 AM
const configMerger = require("C:/users/josh/dev/theshit/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.mjs");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.js")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: ["C:/users/josh/dev/theshit/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/users/josh/dev/theshit/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/users/josh/dev/theshit/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/users/josh/dev/theshit/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/users/josh/dev/theshit/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/users/josh/dev/theshit/plugins/**/*.{js,ts,mjs}","C:/users/josh/dev/theshit/composables/**/*.{js,ts,mjs}","C:/users/josh/dev/theshit/utils/**/*.{js,ts,mjs}","C:/users/josh/dev/theshit/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/users/josh/dev/theshit/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/users/josh/dev/theshit/app.config.{js,ts,mjs}"] }));

module.exports = (() => {const cfg=config;cfg["content"]["23"] = "C:/users/josh/dev/theshit/.nuxt/content-cache/parsed/**/*.{md,yml,yaml,json}";;return cfg;})()
